server:
  port: 80

spring:
  datasource:
    url: jdbc:oracle:thin:@211.238.142.22:1521:XE
    username: hr
    password: happy   
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    database: oracle
    properties: 
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        storage_engine: innodb
        show_sql: true
        format_sql: true
        user_sql_comments: true
  thymeleaf: 
    cache: false
    encoding: UTF-8
    prefix: classpath:templates/
    mode: HTML
    suffix: .html

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind : TRACE